language: php

php:
  - 5.6
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: PREFER_LOWEST=1

    - php: 7.3
      env: CHECKS=1 DEFAULT=0

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction ; fi

  - if [[ $DEFAULT == 1 ]]; then composer require --dev phpunit/phpunit:"^5.7.27|^6.5.12|^7.0" sebastian/diff:"*"; fi

  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction ; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit ; fi

  - if [[ $CHECKS == 1 ]]; then composer phpstan-setup && composer phpstan; fi
  - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi
  - if [[ $CHECKS == 1 ]]; then bin/generate-docs -d ; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
